[mongodb]: enable replicaSet.[key,keySecretName] (#880)
* [mongodb]: enable replicaSet.[key,keySecretName]

As their respected default values were not set, it normally wouldn't fail, but if one of them is set accordingly (to string), helm complains when rendering charts like so:

  Error: values don't meet the specifications of the schema(s) in the following chart(s):
  mongodb:
  - at '/replicaSet/keySecretName': got string, want null
  - at '/replicaSet/key': got string, want null

Setting each type to string allows to set and override each value. Please note, that conditionals referring to those values will still be falsy by default as their default value is an empty string.

* [mongodb]: bump version to 0.9.2

---------

Co-authored-by: Finn Rades <64548817+zOnlyKroks@users.noreply.github.com>