[mongodb] fix a race condition between detect_cluster and Kubernetes Service DNS (#1093)
* [mongodb] fix a race condition between detect_cluster and Kubernetes Service DNS

This change set addresses three issues:

1. attempting to detect a cluster only after the Service DNS resolves
2. properly detecting whether there is an existing replicaset or not
3. working around the chicken/egg problem of the DNS record of the
   Service not being available before the pod(s) enter ready state

The creation of the Service is an asynchronous operation. As a result,
the subsequent mongoshell command may fail, but for a different reason
than intended:

  MongoNetworkError: getaddrinfo ENOTFOUND <headless-service-name>.<namespace>.svc.cluster.local

Checking the DNS availability upfront, solves this issue. Please note,
that as the Service is always rendered and created, there is no need
to limit the amount of iterations of the `until` loop.

Unfortunately, as the pod(s) are not ready at this point (extra-init.sh
did not finished yet), the DNS record in question is not yet created by
Kubernetes. To work around this default behaviour, the immediate
publication of the record is enforced by adding the respective flag to
the ServiceSpec.

Finally, adding this DNS check, makes the `db.version()` check
useless as it's not an appropriate way of finding out whether a
replicaset already exists or not. Which is way, the mongoshell command
has been changed.

* [mongodb] Bump fix version from 8.2.4 to 8.2.5